### ISSUE TITLE
Hoist bounty assignee

### ISSUE THREAD

**Issue by 3commascapital** [pavlovcik/uad-ui#321]
In order to make the bounty assignee easier to find, it may be worth exploring special characters to prepend to the name in an effort to hoist the assignee to the top of the list
![Screen Shot 2022-11-11 at 00 50 50](https://user-images.githubusercontent.com/90629478/201280711-a36d0c7f-ddd0-4bd6-8b39-1d2ed043dea5.png)
![Screen Shot 2022-11-11 at 00 50 56](https://user-images.githubusercontent.com/90629478/201280671-d730e441-0eb0-42dc-91ad-d6bd75ce5927.png)

**Comment by 0x4007** [comment]
I appreciate the suggestion but typing "ub" is an acceptable tradeoff for me vs having a strange name on GitHub. If others on the team support this, please comment below and we can discuss. Otherwise, it has never been brought up in Bounty System related meetings.

https://user-images.githubusercontent.com/4975670/201563703-b9a9c4b5-0b05-42b1-a7fd-107158e3ebdb.mov
