### ISSUE TITLE
incorrect deployment scripts

### ISSUE THREAD

**Issue by zgorizzo69** [pavlovcik/uad-ui#371]
inside contracts/scripts the scripts are referencing bad contract and wrong url e.g. 
- dollar/dollarMintingCalculator.sol instead of src/dollar/core/dollarMintCalculator.sol
- BondingShareV2.sol etc... all these contracts have been remloved/renamed

**Comment by zgorizzo69** [comment]
these scripts should enable us to easily deploy to a fork mainnet for instance (so populating deployments.json inside contracts) that way the ui dapp can easily be bind to these contract and we can test the latest UI with the latest contracts

**Comment by 0x4007** [comment]
Can you set a timeline label on this?

**Comment by zgorizzo69** [comment]
not very familiar with foundry create / deploy so with hardhat it would take one day but here maybe a bit more

**Comment by cuddle-dev** [comment]
> not very familiar with foundry create / deploy so with hardhat it would take one day but here maybe a bit more

If we use hardhat to deploy contracts, it will not take much time but we've already migrated into foundry fully. so we need to create any scripts using `foundry create`

**Comment by zgorizzo69** [comment]
> 

Sure that was the plan 😜

**Comment by sergfeldman** [comment]
@zgorizzo69 https://etherscan.io/tx/0x3ab00f8aa4813c1aaf91ebff42950045ad7a362510b3354a2237491df21a6ff7

**Comment by 0x4007** [comment]
> @zgorizzo69 https://etherscan.io/tx/0x3ab00f8aa4813c1aaf91ebff42950045ad7a362510b3354a2237491df21a6ff7

This isn't completed why was this paid out?

**Comment by sergfeldman** [comment]
> > @zgorizzo69 https://etherscan.io/tx/0x3ab00f8aa4813c1aaf91ebff42950045ad7a362510b3354a2237491df21a6ff7
> 
> This isn't completed why was this paid out?

The payout was made because @zgorizzo69 requested the payment for this issue.

**Comment by zgorizzo69** [comment]
I did the job intended for that duration meaning  removing the old scripts and fixing all the deployment scripts for the new contracts 
+ as I said and I think you agreed it makes more sense to write a full deployment script (meaning a script that will call the one I fixed in the right order but it is something that you can do now manually thx to this fix ) in the diamond than here 
but it is true that now we realized that the diamond needed more work

**Comment by 0x4007** [comment]
> https://etherscan.io/tx/0x3ab00f8aa4813c1aaf91ebff42950045ad7a362510b3354a2237491df21a6ff7

The linked PR isn't merged so the bounty is not complete. Bounties are only intended to be paid for completed work. 

- If issues are closed before the solution is produced, due to some context not present on the GitHub, then project management won't scale beyond a single manager. 
- If payments are released before the solution is produced, then integrity with our accounting will be damaged.

When do you anticipate that we will merge the PR?

>  it makes more sense to write a full deployment script 

Yes because without a full deployment script we have issues like https://github.com/ubiquity/ubiquity-dollar/pull/351 as blockers (can't use the UI unless we redeploy the new contract method names etc.) At minimum we would need a README (or even just a shell script) to chain the deploys together in the right order on a local Anvil chain.

**Comment by zgorizzo69** [comment]
> 

IMO we can close this PR asap and create another issue specifically for a full local deployment script for test purposes. We have to specify what should be deployed (only core ? + Ubiquity chef ? Metapool or metapool mock ?) and what accounts should be provisioned (would be handy to have some accounts with LP , dollar, DAI to test the UI). Note that it will not fix the UI as some PR like #351 can break it
