### ISSUE TITLE
Smart Contract MVP: UBQ bonding curve to burn UBQ and mint NFTs

### ISSUE THREAD

**Issue by sergfeldman** [pavlovcik/uad-ui#430]
To do
Implement the logic "Buy with any token" according to the discussion
https://github.com/ubiquity/ubiquity-dollar/discussions/428

The issue is related to 
https://github.com/ubiquity/ubiquity-dollar/issues/429
https://github.com/ubiquity/ubiquity-dollar/issues/434

**Comment by Hendobox** [comment]
I am interested in this task. I will get on it with your approval. This should be my first contribution, and I am looking forward to distinguishing myself.

**Comment by sergfeldman** [comment]
> I am interested in this task. I will get on it with your approval. This should be my first contribution, and I am looking forward to distinguishing myself.

Hey @Hendobox before you get assigned:
- This issue will be devided to smaller issues with separate pricing.
- This issue relates to #429 

@Hendobox Meanwhile, if you have clarifing questions on this issue, please post them here https://github.com/ubiquity/ubiquity-dollar/discussions/428

**Comment by Hendobox** [comment]
> > I am interested in this task. I will get on it with your approval. This should be my first contribution, and I am looking forward to distinguishing myself.
> 
> Hey @Hendobox before you get assigned:
> 
> * This issue will be devided to smaller issues with separate pricing.
> * This issue relates to [UI component: UBQ bonding curve to burn UBQ and mint NFTs #429](https://github.com/ubiquity/ubiquity-dollar/issues/429)
> 
> @Hendobox Meanwhile, if you have clarifing questions on this issue, please post them here #428

Oh, okay cool. 

One question though, could you direct me to the actual smart contract where I will be adding the functionalities so I can sync with the existing codebase? Thanks

**Comment by FibrinLab** [comment]
Still an active issue? Would love to get assigned this.

@sergfeldman

**Comment by FibrinLab** [comment]
I would love to make suggest a pull request for this. Still active @sergfeldman @pavlovcik

**Comment by 0x4007** [comment]
@sergfeldman you should include context/the title at least next to your referenced issues because its confusing for me to follow a chain of these
<img width="163" alt="Screenshot 2023-01-02 at 09 15 20" src="https://user-images.githubusercontent.com/4975670/210189362-e768282b-b82f-45cc-b0bd-14a1f33eb8db.png">

---

> I would love to make suggest a pull request for this. Still active @sergfeldman @pavlovcik

Yes but to clarify we have two parts of this. The first part must be completed first, and then the second part is possible. You are able to do only the first part and not do the second part if you wish.

1. The first part is to fork a bonding curve smart contract. Please let us know which you plan to work with and why before beginning. Along with this, you must make a UI to interact with this smart contract (it likely will simply be a deposit UBQ input field with a submit button.)

2. The second part is to make another UI that will leverage Uniswap to make it more convenient for users to mint a UbiquiStick even if they do not own UBQ. The Solidity development would be minimal as it would simply be a function to swap on Uniswap from any asset to UBQ, and then call the mint function by depositing that UBQ. This will be more involved in the UI because it should also query the uniswap-router for price estimation.

---

Comment here which bonding curve contract you plan to fork and then if there are no issues with your selection based on the discussion here, I'll assign you! @FibrinLab

**Comment by FibrinLab** [comment]
@sergfeldman For the issues I understand simple deposit UBQ and mint NFT contract. I would like to work on this using a fork from Bancor Protocol. https://github.com/bancorprotocol/contracts

**Comment by 0x4007** [comment]
One small detail: we should be able to recover the UBQ from the bonding curve. The plan is that we can do more with the tokens, like manually add it as liquidity in the market. You should be able to copy the access control code `UBQ_MINTER` or something like that from another contract to enable this method only for the admin wallet.

**Comment by 0x4007** [comment]
https://etherscan.io/tx/0xda3cd905c7a6b40a2effa41a5d96ce4919afe6047e5fc25b963be754e7863a44
