### ISSUE TITLE
Update Workflow Permissions

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#441]
> Currently unable to use my computer at the moment
> 
> I tried merging but got this error so will try again later.
> 
> @0xcodercrane perhaps some config was changed in your CI?
> 
> Be sure to post your wallet address on the issue (not this PR) @FibrinLab
> 
> ![image](https://user-images.githubusercontent.com/4975670/209984917-21176b81-79b3-45c1-b849-a9e6faad6952.png)

Since this PR modifies the workflow, your OAuth token doesn't have workflow modification permission.
![image](https://user-images.githubusercontent.com/109317559/210002307-d0c5b3ab-b7cc-47c9-bd8c-2ba038a081c5.png)

More info: [How to resolve "refusing to allow an OAuth App to create or update workflow" on git push](https://stackoverflow.com/questions/64059610/how-to-resolve-refusing-to-allow-an-oauth-app-to-create-or-update-workflow-on)
@pavlovcik 

_Originally posted by @Steveantor in https://github.com/ubiquity/ubiquity-dollar/pull/426#issuecomment-1367537438_

**Comment by 0x4007** [comment]
@Steveantor you seemed knowledgable on this issue. Perhaps I can assign it to you and work with you to test that it is solved?

**Comment by Steveantor** [comment]
> @Steveantor you seemed knowledgable on this issue. Perhaps I can assign it to you and work with you to test that it is solved?

sure I can be assigned to this.
@pavlovcik

**Comment by Steveantor** [comment]
### Deep dive down:
GitHub Clients use multiple authentication methods:

> **OAuth Apps**
> **Personal access tokens:** [Fine-grained tokens, Classic tokens]
> **Traditional Authorization** (user: pass)

to communicate with the server to handle
`issues`, `pull_requests`, `notifications ` etc.

The issue here is that both GitHub Desktop and GitHub Mobile (and other git clients) usually use OAuth,
but with a slight variation in the permissions.

> ![Screenshot 2023-01-02 191448x](https://user-images.githubusercontent.com/109317559/210271206-ea3911c9-5fc1-4eae-b511-d74df5c1437a.png)

GitHub Desktop requests the `_update github action workflows_` permission.

> ![image](https://user-images.githubusercontent.com/109317559/210268177-ed2f628d-d64a-4d76-bd5c-2b6178bbbda5.png)

GitHub Mobile (Android) doesn't do that.


This causes GitHub Mobile fails to merge any commits that modify the _.github/workflows/*.yml_,
due to insufficient OAuth permissions.

Unfortunately, GitHub doesn't support modifying OAuth App's permissions.
we could take some alternative approaches to deal with this issue as shown below.


### Generate Classic tokens:

> [Personal access tokens (classic)
> ](https://github.com/settings/tokens)
> ![image](https://user-images.githubusercontent.com/109317559/210270866-246e0cfe-0084-4c20-b132-e8485f07228e.png)

workflow: Update GitHub Action workflows

### Generate Fine-grained tokens (Beta):

> [Fine-grained personal access tokens](https://github.com/settings/tokens?type=beta)
> ![image](https://user-images.githubusercontent.com/109317559/210272119-1c6e8aee-6bef-4922-a2f7-1190952e6dca.png)

Workflows: Update GitHub Action workflow files.

\
\
Solutions:
1. Use GitHub Web (or a client that supports `user: pass`)
2. Use alternative GitHub clients

⚠GitHub Mobile doesn't support personal access tokens at the time (tested on [GitHub for Android](https://play.google.com/store/apps/details?id=com.github.android))⚠

There are two Mobile clients that work pretty well.

### OctoDroid:

> [OctoDroid for GitHub
> ](https://play.google.com/store/apps/details?id=com.gh4a)
> ![image](https://user-images.githubusercontent.com/109317559/210273970-e9f877d5-71fc-4d59-8187-fe8c07684ed6.jpg)

### ForkHub

> [ForkHub for GitHub
> ](https://play.google.com/store/apps/details?id=jp.forkhub)
> ![image](https://user-images.githubusercontent.com/109317559/210274156-8ab11a3a-50e9-49ba-98f2-c8472a5dcf5d.jpg)

username: `<space>`
password: `<personal_access_token>`

@pavlovcik

**Comment by 0x4007** [comment]
@Steveantor thanks for the write up. I'll check out the other clients and we can consider this issue solved. Please share your address. Thanks!

**Comment by Steveantor** [comment]
Here's my address:
`0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE`
@pavlovcik

**Comment by 0x4007** [comment]
> Here's my address: `0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE` @pavlovcik

https://etherscan.io/tx/0x8316371e9de08e28fb08d1ea8f0caa1abcd44c63b5cc13ca2c9654a1f32ecb7c
https://etherscan.io/tx/0xbc267a79fc4966c6d2c8a017de1970cea1d8380784f730edfd82abe9b0a261af
