### ISSUE TITLE
Remove tests for ERC4624

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#481]
Remove:

- https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/test/dollar/ERC4626.t.sol
- https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/mocks/MockERC4626.sol

**Comment by Hendobox** [comment]
Will take on this for my first task as I understand the code base

**Comment by sergfeldman** [comment]
> Will take on this for my first task as I understand the code base

@rndquu Are you ok that @Hendobox will be assigned to this bounty?

**Comment by 0x4007** [comment]
Wait, if its just deleting two files we shouldn't be paying $100 for that. 

I guess its too late because we already have an open PR. I should have checked the new issues created (which I implicitly approved) more carefully. To fix this part of the process, @rndquu next time you create bounties, please continue to set time estimates, and priorities. However let me assign to @ubiquity-bounties in order to officially approve and release the bounties to the DevPool.

**Comment by rndquu** [comment]
> > Will take on this for my first task as I understand the code base
> 
> @rndquu Are you ok that @Hendobox will be assigned to this bounty?

sure

**Comment by rndquu** [comment]
> Wait, if its just deleting two files we shouldn't be paying $100 for that.
> 
> I guess its too late because we already have an open PR. I should have checked the new issues created (which I implicitly approved) more carefully. To fix this part of the process, @rndquu next time you create bounties, please continue to set time estimates, and priorities. However let me assign to @ubiquity-bounties in order to officially approve and release the bounties to the DevPool.

the smallest time estimate we have is "<1 Day"

we have a "time precision" feature in the bot's issues https://github.com/ubiquity/bounty-bot/issues/77 but it is not yet implemented

**Comment by Eren-Yeaager** [comment]
Hi can u assign me this issue. I was not able to do diamond optimization but i want to contribute to ubiquity pay.

**Comment by rndquu** [comment]
@Eren-Yeaager hi, this issue is already solved, so @pavlovcik we can close it
