### ISSUE TITLE
CI Build Test off Current PR vs `development`

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#505]
In an effort to make CI more reliable, what if we added a new CI action that will checkout the current PR instead of `development`? That way, the build will reflect the updated filenames?

I'm just speculating here I haven't done deep research on the topic.

---

> CI isn't working because I changed the filenames (NFT -> Nft). Perhaps we could have another CI test that runs on the current PR vs off of development?

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/504#issuecomment-1396780812_

**Comment by 0x4007** [comment]
@rndquu could you add your opinion here?

**Comment by rndquu** [comment]
> @rndquu could you add your opinion here?

I can't understand what you mean by "checkout the current PR instead of development"

When user creates a PR then "install and build" action runs against the branch where PR was created which already includes changes from the `development` branch

Right now the `development` branch is successfully built without errors so the best we can do is just stop merging PRs with failing CI checks

**Comment by 0x4007** [comment]
> I can't understand what you mean by "checkout the current PR instead of development"

The context is in the linked comment. You can see I renamed files and now the CI is broken because of the renamed files.

**Comment by 0x4007** [comment]
Git doesn't track filename capitalization changes so I was confused/misinformed when I made this issue.
