### ISSUE TITLE
fix `operator-filter-registry`

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#542]
We need to commit a copy to our repo because the dependency randomly fails to install even on a CI rerun where it originally worked.

Make sure to get it to work with `forge` and make sure to commit the related to the repo. Bonus if you can figure a better solution vs committing the code, but we can't rely on external dependency management if this is failing the way that it is. 

> so i just re-ran the ci on @rndquu’s commit (the build originally passed)

> i’m getting that DefaultOperatorFilterer.sol error again which means that they changed something on the code maintainer’s side. again, i simply re-ran the same code’s ci (which originally passed) and now its failing.

> Failed to resolve file: "/home/runner/work/ubiquity-dollar/ubiquity-dollar/packages/contracts/lib/operator-filter-registry/DefaultOperatorFilterer.sol": No such file or directory (os error 2).

> https://github.com/ubiquity/ubiquity-dollar/actions/runs/4055656948/jobs/7067754856

> this seems like a really shitty way to maintain a codebase if we have brittle dependencies. should we just commit the file directly to our repo instead?

**Comment by 0x4007** [comment]
#542 related research but no dice yet

**Comment by 0x4007** [comment]
@rndquu please share your address here

**Comment by rndquu** [comment]
0x336C033842FA316d470e820c81b742e62A0765DC

**Comment by 0x4007** [comment]
> 0x336C033842FA316d470e820c81b742e62A0765DC

https://etherscan.io/tx/0x47c2859e002ce92aad217e91d54fa744ecf58a40c83dc1149d9788e1cf0f07e3
https://etherscan.io/tx/0x3dec5f755240a593c773fe9160956259b87502df0e6c6754f20534556d25348d

**Comment by 0x4007** [comment]
Can you share additional detail on the Foundry update that broke it? I want to know what the update was and why it broke it so we can prevent something like this happening in the future again. Or at least know how to quickly solve it. https://github.com/ubiquity/ubiquity-dollar/pull/546#issue-1572492057


> fixes `development` branch build
> 
> 1. The "operator-filter-registry issue" was caused by recent foundry update
> 2. This line https://github.com/rndquu/ubiquity-dollar/blob/ed010f5a6d0137a36f9fc3447b60bb166269e5e1/packages/dapp/package.json#L15 fixes this error https://github.com/rndquu/ubiquity-dollar/actions/runs/4101383336/jobs/7073110768
> 3. Removed UI test script because there is no such file `dapp/test/puppeteer.ts `

**Comment by rndquu** [comment]
How it was:
1. I ran `yarn build:all` and the script worked fine without any errors
2. Then I updated foundry via `foundryup` (as the ci action uses the latest foundry version)
3. Then I ran `yarn build:all` again and got this error:
```
Failed to resolve file: "/home/runner/work/ubiquity-dollar/ubiquity-dollar/packages/contracts/lib/operator-filter-registry/DefaultOperatorFilterer.sol": No such file or directory (os error 2).
```

All forge dependencies live in `packages/contracts/lib` as submodules.

Now check this line https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/ubiquistick/UbiquiStick.sol#L8

This is a wrong path, instead of `operator-filter-registry/DefaultOperatorFilterer.sol` it should be `operator-filter-registry/src/DefaultOperatorFilterer.sol`.

When foundry finds such a path it tries to find it itself (I guess there is some recursive search similar to npm and node_modules). And it seems that older foundry versions were able to find out `DefaultOperatorFilterer` using the "wrong" path but the newest foundry version throws an error.

There are 2 ways to prevent such errors:
1. Use `remappings.txt` (as implemented here https://github.com/ubiquity/ubiquity-dollar/pull/546)
2. Use correct import paths (here https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/ubiquistick/UbiquiStick.sol#L8 it should be `operator-filter-registry/src/DefaultOperatorFilterer.sol` but thanks to `remappings.txt` foundry is able to find the file)

**Comment by zgorizzo69** [comment]
fyi I fixed a problem linked to typechain generating several test.sol contract because of several imported repository inside `/lib` having a contract named test.sol 
here is the fix inside dapp/package.json
```
 "build:types": "typechain --show-stack-traces --target ethers-v5 ../contracts/out/**/[!(test.sol)]*/*.json --out-dir=types"
```

**Comment by 0x4007** [comment]
Yes its already in @rndquu this pull request

> fyi I fixed a problem linked to typechain generating several test.sol contract because of several imported repository inside `/lib` having a contract named test.sol here is the fix inside dapp/package.json
> 
> ```
>  "build:types": "typechain --show-stack-traces --target ethers-v5 ../contracts/out/**/[!(test.sol)]*/*.json --out-dir=types"
> ```

**Comment by 0x4007** [comment]
> Then I updated foundry via foundryup (as the ci action uses the latest foundry version)

Should we lock the foundry version in our CI then? @zgorizzo69 @rndquu 

> Use correct import paths (here https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/ubiquistick/UbiquiStick.sol#L8 

We should just use the correct import paths.

**Comment by rndquu** [comment]
We already use incorrect import paths, at least for these libs https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/remappings.txt

There are 2 ways:
1. Leave it as is (use `remappings.txt` like we do now)
2. Remove `remappings.txt` and use correct paths everywhere

I don't see any hurdles in using `remappings.txt` but if we get such build errors then we should go with option №2

**Comment by 0x4007** [comment]
If remappings isn't mandatory I think we should remove it to simplify things and to avoid confusion down the road.

**Comment by zgorizzo69** [comment]
we have remapping all over the place it increases readability    
what imports are incorrect @rndquu ?
we should at least not use nightly but a stable release @pavlovcik

**Comment by 0x4007** [comment]
> we should at least not use nightly but a stable release @pavlovcik

Stable ok. If its an issue again for some reason, then we lock the version.
