### ISSUE TITLE
Gas optimization, reentrancy, unused variable and unused code after a return statement was called

### ISSUE THREAD

**Issue by malik672** [pavlovcik/uad-ui#684]
1.Many of the functions can be reduced to view or pure , this will probably save you 20x the original gas fees used
2. There is a potential renetrancy in using openzepplin onERC1155received when you make external calls to another address
3. there are a lot of unused variable in the contract this will 100% increase gas fees 
4. a lot of variables are being shadowed, this will 100% result in the contract being exploited 
5. there's a function that updates a state variable after the return statement, this won't work because everything after a return variable won't work
6. You can probably reduce gas fees for this contract by 76% with the introduction of assembly and bitwise operation
7. There might be more, but this is what i've seen

**Comment by 0x4007** [comment]
Thanks for filing this issue.

2. should be validated before we make a bounty for it. 
3. linters should handle this
4. linters handle this. 
5. which function?
6. this is very unlikely to be the decision we make because code maintainability is more important. However, it could be interesting to optimize the popular functions.

**Comment by rndquu** [comment]
> 1.Many of the functions can be reduced to view or pure , this will probably save you 20x the original gas fees used 2. There is a potential renetrancy in using openzepplin onERC1155received when you make external calls to another address 3. there are a lot of unused variable in the contract this will 100% increase gas fees 4. a lot of variables are being shadowed, this will 100% result in the contract being exploited 5. there's a function that updates a state variable after the return statement, this won't work because everything after a return variable won't work 6. You can probably reduce gas fees for this contract by 76% with the introduction of assembly and bitwise operation 7. There might be more, but this is what i've seen

hi, thank you for creating an issue

1. we will leave it for the "gas optimisation" task
2. you are free to create a PR with POC and fix, I think @pavlovcik will set a bounty accordingly
3. we will leave it for the "gas optimisation" task
4. we will leave it for the "slither analysis" task
5. which one?
6. we will leave it for the "gas optimisation" task

**Comment by malik672** [comment]
@pavlovcik @rndquu
```
   /// @notice returns the percentage of deviation from the peg multiplied by amount
    //          when Ubiquity Dollar is <1$
    function _getPercentDeviationFromUnderPeg(
        uint256 amount
    ) internal returns (uint256) {
        uint256 curPrice = _getTWAPPrice();
        if (curPrice >= 1 ether) {
            return 0;
        }

        bytes16 res = _one.sub(curPrice.fromUInt()).mul(amount.fromUInt());
        // returns (1- TWAP_Price) * amount.
        return res.div(_one).toUInt();
        LibTWAPOracle.update();
    }
```
that's the function

**Comment by malik672** [comment]
for the reentrancy here's an article https://samczsun.com/the-dangers-of-surprising-code/

**Comment by rndquu** [comment]
To sum up:
1. `view/pure/unused variables/shadowing`: this will be handled as a part of "slither: fix warnings" task
2. `potential reentrancy`: you are free to create a PR with POC and fix
3. gas optimisations will be handled in a later project stage

**Comment by malik672** [comment]
@rndquu  there's still one, just saw it now

**Comment by malik672** [comment]
saw this code in the addressUtils library   
 ```
 function isContract(address account) internal view returns (bool) {
        uint256 size;
        assembly {
            size := extcodesize(account)
        }
        return size > 0;
    }
```
this does not work if the calller calls the function from the constructor, i think when redesigning, it should be removed since it just increases code size

**Comment by 0x4007** [comment]
If it is not being used anywhere then I think we can probably remove it.

```
Searching "isContract"
 
6 results - 2 files

packages/contracts/src/dollar/libraries/AddressUtils.sol:
  20  
  21:     function isContract(address account) internal view returns (bool) {
  22          uint256 size;

  81      ) private returns (bytes memory) {
  82:         if (!isContract(target)) revert AddressUtils__NotContract();
  83  

packages/contracts/test/helpers/DiamondTestHelper.sol:
  19          string memory _name,
  20:         bool _isContract
  21      ) internal returns (address) {
  22:         return generateAddress(_name, _isContract, 0);
  23      }

  26          string memory _name,
  27:         bool _isContract,
  28          uint256 _eth

  34  
  35:         if (_isContract) {
  36              vm.etch(newAddress_, "Generated Contract Address");
```

**Comment by rndquu** [comment]
> saw this code in the addressUtils library
> 
> ```
> function isContract(address account) internal view returns (bool) {
>        uint256 size;
>        assembly {
>            size := extcodesize(account)
>        }
>        return size > 0;
>    }
> ```
> 
> this does not work if the calller calls the function from the constructor, i think when redesigning, it should be removed since it just increases code size

[AddressUtils](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/libraries/AddressUtils.sol) is basically a copy/paste code of the openzeppelin's [Address](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.9.2/contracts/utils/Address.sol) library

The latest openzepplin's version `4.9.2` still has the `isContract()` [method](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/libraries/AddressUtils.sol#L21)

Having a library which has the `isContract()` method is not a vulnerability. The vulnerability arises when you use the `isContract()` incorrectly

I think we can keep [AddressUtils](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/libraries/AddressUtils.sol) untouched because:
- openzeppelin has this method in their lib
- we don't use the `isContract()` anywhere
- unused `isContract()` doesn't increase the result bytecode (because it is not used anywhere in the contracts)

Should somebody implement the `isContract()` somewhere in the code we will keep it mind that this check can be circumvented in the constructor

**Comment by malik672** [comment]
@rndquu you don't have to use it to lead to increase in bytecode, once you import the contract, it's already leads to an increase in bytecode, I understand the reason not to remove it since removing it, might probably affect other stuffs

**Comment by 0x4007** [comment]
For whatever it's worth, I'm far more concerned with increased gas costs related to regular usage versus the initial deployment.

**Comment by rndquu** [comment]
> @rndquu you don't have to use it to lead to increase in bytecode, once you import the contract, it's already leads to an increase in bytecode, I understand the reason not to remove it since removing it, might probably affect other stuffs

https://github.com/ethereum/solidity/issues/13349
