### ISSUE TITLE
Move `CreditClock` to diamond facets

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#772]
We've migrated most of our contracts to the diamond proxy implementation. But not all of them.

What should be done:
- refactor [CreditClock](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/core/CreditClock.sol) to be part of the diamond [facets](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/facets) 
- add `CreditClock` to the [deployment script](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/scripts/deploy/dollar/solidityScripting)
- refactor `CreditClock` [tests](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/test/dollar/core/CreditClock.t.sol) accordingly

**Comment by molecula451** [comment]
I'm getting rid of this test https://github.com/ubiquity/ubiquity-dollar/blob/c119128ef92a5b042f5b136364eda9f537600f80/packages/contracts/test/dollar/core/CreditClock.t.sol#L80

and it's child functions, because, it's a blocker, and it was originally intented to mimick a behaviour to the replaced CreditClock and not the facet itself, besides this "test" I would consider it really bad and it's not suitable to keep it in anyway. I would consider the [new refactored](https://github.com/ubiquity/ubiquity-dollar/blob/613c065653ad1b8c4478d1538f5101ee8652b184/packages/contracts/test/diamond/facets/CreditClockFacet.t.sol) tests as usefuls, because it actually make the calls to the functions and that's it

we could add broader testing at #812
