### ISSUE TITLE
UI: apply diamond to credits page

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#786]
Original [issue](https://github.com/ubiquity/ubiquity-dollar/issues/783)

What should be done:
- take this [file](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/lib/hooks/contracts/use-protocol-contracts.ts) and refactor the [credits](https://uad.ubq.fi/credits) page to use contracts from the new diamond architecture

**Comment by gitcoindev** [comment]
I would like to give it a try.

**Comment by bojan07** [comment]
[This PR](https://github.com/ubiquity/ubiquity-dollar/pull/809) is also ready for a review @rndquu @molecula451

**Comment by bojan07** [comment]
[Uniswap smart order router package issue](https://github.com/ubiquity/ubiquity-dollar/pull/809#issuecomment-1752572290) is really hopeless in my case. I have tested alpha router with several versions, but all implementation keep returning same error 🤷‍♀️

I have opened [an issue](https://github.com/Uniswap/smart-order-router/issues/427) in the uniswap smart order router repo.

I'm wondering if this error is generated because uniswap smart order router package is not compatible with anvil testnet, and this error might disappear with mainnet

**Comment by molecula451** [comment]
https://github.com/ubiquity/ubiquity-dollar/pull/804#issuecomment-1760367675
https://github.com/ubiquity/ubiquity-dollar/pull/804#issuecomment-1760378041

**Comment by bojan07** [comment]
@rndquu @molecula451 According to the review of https://github.com/ubiquity/ubiquity-dollar/pull/804, can I think that this issue spec has also implemented?

**Comment by molecula451** [comment]
Please wait, till we re-organize stuff with the recent commits

**Comment by bojan07** [comment]
> Please wait, till we re-organize stuff with the recent commits

While you are re-organizing this stuff, which issue do you want me to work on? What's the priority?

**Comment by bojan07** [comment]
@molecula451 [last merged PR](https://github.com/ubiquity/ubiquity-dollar/pull/804) also meet the specification of this issue as well as #785 according to your review, as I see.
Since you mentioned "re-organizing stuff", and closed my [new PR](https://github.com/ubiquity/ubiquity-dollar/pull/819), I felt you have some opinion for me to finish the work for this issue. Please update me so that I can finish this issue soon and move on next one
@rndquu I expect your comments too

**Comment by bojan07** [comment]
> @molecula451 [last merged PR](https://github.com/ubiquity/ubiquity-dollar/pull/804) also meet the specification of this issue as well as #785 according to your review, as I see. Since you mentioned "re-organizing stuff", and closed my [new PR](https://github.com/ubiquity/ubiquity-dollar/pull/819), I felt you have some opinion for me to finish the work for this issue. Please update me so that I can finish this issue soon and move on next one @rndquu I expect your comments too

👀👀👀
