### ISSUE TITLE
Rivet

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#791]
"React DevTools for crypto" from Paradigm

https://twitter.com/keyrxng/status/1696579627756449864 

@Keyrxng do you think it makes sense for us to add Rivet instead?

**Comment by Keyrxng** [comment]
I was going to suggest that when I saw it but it will require viem and wagmi upgrades for sure if trying to embed it somehow otherwise have it included in dev flow as a standalone tool to use. That's why I didn't think it was worth re-suggesting due to the previous talk on viem etc. But as a standalone it would benefit devs far more than what I was able to pipe into the UI as I didn't know of [EIP-6963](https://eips.ethereum.org/EIPS/eip-6963) until after I saw Rivet if I'm being honest. And it just has a shitton of data visualization which there isn't much of other than the anvil console in what I pushed but Rivet I believe trumps that. 

- https://www.paradigm.xyz/oss/viem
- https://www.paradigm.xyz/2022/11/paradigm-and-wagmi

- https://github.com/paradigmxyz/rivet

**Comment by rndquu** [comment]
Rivet is a browser extension that calls the same anvil's "cheat" RPC methods as already implemented in this [issue](https://github.com/ubiquity/ubiquity-dollar/issues/528). It doesn't require any special integration on our side so Rivet can be used as a standalone dev tool.

**Comment by 0x4007** [comment]
> I was going to suggest that when I saw it but it will require viem and wagmi upgrades for sure if trying to embed it somehow otherwise have it included in dev flow as a standalone tool to use. That's why I didn't think it was worth re-suggesting due to the previous talk on viem etc. But as a standalone it would benefit devs far more than what I was able to pipe into the UI as I didn't know of [EIP-6963](https://eips.ethereum.org/EIPS/eip-6963) until after I saw Rivet if I'm being honest. And it just has a shitton of data visualization which there isn't much of other than the anvil console in what I pushed but Rivet I believe trumps that.
> 
> * https://www.paradigm.xyz/oss/viem
> * https://www.paradigm.xyz/2022/11/paradigm-and-wagmi
> * https://github.com/paradigmxyz/rivet

Talked to the creator of TypeChain (he came over to my house during Korea Blockchain Week lol) and he said that it is [now deprecated](https://twitter.com/krzKaczor/status/1721936603919032415) in favor of viem. 

@rndquu something to consider if our current tech stack becomes an issue.
