### ISSUE TITLE
Gas optimization for Ubiquity contracts

### ISSUE THREAD

**Issue by 0xRizwan** [pavlovcik/uad-ui#895]
Hi,

I have done gas optimization on contracts in development branch.

Link to check the gas optimization changes- https://github.com/ubiquity/ubiquity-dollar/compare/development...0xRizwan:ubiquity-dollar-Gas-optimization:development

**Total gas saved from current implementation contracts- 13_38_283**

cc- @pavlovcik and @molecula451

**Comment by 0x4007** [comment]
How long does something like this take to do?

Also @rndquu @gitcoindev rfc

**Comment by rndquu** [comment]
> How long does something like this take to do?
> 
> Also @rndquu @gitcoindev rfc

I would put ~4 hours

**Comment by molecula451** [comment]
i'm likely good with `require()` i would focus in gas optimizations in edges such as:

- Minting
- Deposit
- Withdraw

Overall user experience but at the same time preserving what we architecturally like in terms of code definition.

Perhaps we would like to upgrade to Erroring Support or not

**Comment by 0xRizwan** [comment]
> > How long does something like this take to do?
> > Also @rndquu @gitcoindev rfc
> 
> I would put ~4 hours

Hey, 

Thanks for the comment. This would definitely need ~6 hours. The tests also required to be changed. To be noted all tests are passed shared in above link.

**Comment by 0xRizwan** [comment]
> i'm likely good with `require()` i would focus in gas optimizations in edges such as:
> 
> * Minting
> * Deposit
> * Withdraw
> 
> Overall user experience but at the same time preserving what we architecturally like in terms of code definition.
> 
> Perhaps we would like to upgrade to Erroring Support or not

custom errors are preferred over require/assert. This definately saves gas with use of custom errors. In case of require, i see the string message length was more than 32 bytes at some instances which means additional 1 slot is required in such case. Instead of using more than 1 slot for just return string message, i would still prefer custom errors. To be noted, custom errors has not been used fully in all contracts, at some places require is kept too.

I believe the contracts is being deployed on Ethereum mainnet. For user experience, i would request to see the possibility of L2 deployment. This definately increases number of users using the protocol due to low fees and the users frequently using functions  like Minting, Deposit, Withdraw would incur very very low gas as compared to Ethereum.

For example:
Taking my real life example. On average, I pay 4$ for Ethereum transaction and 0.25$ for Arbitrum transaction.

**Comment by molecula451** [comment]
> custom errors are preferred over require/assert. This definately saves gas with use of custom errors. In case of require, i see the string message length was more than 32 bytes at some instances which means additional 1 slot is required in such case. Instead of using more than 1 slot for just return string message, i would still prefer custom errors. To be noted, custom errors has not been used fully in all contracts, at some places require is kept too.

I'm sure custom errors are better implementation, consider this as a refactor, but changing to custom errors could be considered a refactor, instead of some gas optimization as there are `require()` working very good tho, feel free to start working on the issue

**Comment by 0x4007** [comment]
@0xRizwan Make sure to set your wallet address first. I think that's the unhandled error.

**Comment by molecula451** [comment]
> I believe the contracts is being deployed on Ethereum mainnet. For user experience, i would request to see the possibility of L2 deployment. This definately increases number of users using the protocol due to low fees and the users frequently using functions like Minting, Deposit, Withdraw would incur very very low gas as compared to Ethereum.

Hey We are going Mainnet, so consider that do not take in count L2s

**Comment by molecula451** [comment]
custom erros can also be inside `require()` that's why the change could be considered a refactor

**Comment by 0xRizwan** [comment]
Please check [PR](https://github.com/ubiquity/ubiquity-dollar/pull/896)

**Overall gas change from current implementation: 6.6 million  which is ~2.3 % change**.

Feel free to connect for any clarifications.

**Comment by 0x4007** [comment]
I'll try salvaging the permits from the logs here.

**Comment by 0x4007** [comment]
<details>
    <summary>
      <b
        ><h3>
          <a
            href="https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiIxODMwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjczNTc1OTg1MjU1NzEwOTk0NzcxOTU3MTA2ODkxOTk2NjQyOTI0MjEwMDI4MTgyNjcxMjg1NjgxNDA3OTM2NDExMzQ1NjI2OTA0ODg1IiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHg0MDA3Q0UyMDgzYzdGM0UxODA5N2FlQjNBMzliYjhlQzE0OWEzNDFkIiwicmVxdWVzdGVkQW1vdW50IjoiMTgzMDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweDQ0Q2ExNURiMTAxZkQxYzE5NDQ2N0RiNkFGMGM2N0M2QmJGNEFCNTEiLCJzaWduYXR1cmUiOiIweDE4NWRkNjBiZWJjZDllMDI4ZGQ3ODE3MTUxZmRiNDVhYWIyMGY1Yjg1YTUyNzIyZWRlZjFjMWI4YTQ1ZWRhNTg1ZTBjNjA4N2RmNDBmMGE2Njc0N2E1ZDA3YmJiOGYwYTRkMTNjNTk2MzA4MTQ5ODhjMDZkNzAzMTRlYTBkMWRiMWIiLCJuZXR3b3JrSWQiOjEwMH1d"
          >
            [ 18.3 WXDAI ]</a
          >
        </h3>
        <h6>@pavlovcik</h6></b
      >
    </summary>
    <h6>Contributions Overview</h6>
<table><thead>
<tr><th>View</th><th>Contribution</th><th>Count</th><th>Reward</th>
</thead><tbody>
<tr><td>Issue</td><td>Comment</td><td>3</td><td>3.7</td></tr>
<tr><td>Review</td><td>Comment</td><td>3</td><td>14.6</td></tr>
</tbody></table>
    <h6>Conversation Incentives</h6><table><thead><tr><th>Comment</th><th>Formatting</th><th>Relevance</th><th>Reward</th></tr></thead><tbody><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/895#issuecomment-1939522450">How long does something like this take to do?

Also @rndquu @git...</a></h6></td><td>1.3</td><td>0.49</td><td>1.3</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/895#issuecomment-1940426573">@0xRizwan Make sure to set your wallet address first. I think th...</a></h6></td><td>1.6</td><td>0.44</td><td>1.6</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/895#issuecomment-1945971742">I'll try debugging the permit flow here. ...</a></h6></td><td>0.8</td><td>0.45</td><td>0.8</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/pull/896#issuecomment-1943199822">> `require` used with return string message adds more readabilit...</a></h6></td><td><details><summary>4.4</summary>
<pre>a:
  count: 1
  score: "1"
  words: 1
code:
  count: 1
  score: "1"
  words: 1
</pre>
</details></td><td>0.75</td><td>4.4</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/pull/896#issuecomment-1944462070">> i think we could perhaps compensate the user for these comment...</a></h6></td><td>4.4</td><td>0.57</td><td>4.4</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/pull/896#issuecomment-1944522511">Yes unfortunately the permit flow is a coin toss right now. I th...</a></h6></td><td><details><summary>5.8</summary>
<pre>li:
  count: 1
  score: "1"
  words: 8
</pre>
</details></td><td>0.56</td><td>5.8</td></tr></tbody></table>
  </details>
  

  <details>
    <summary>
      <b
        ><h3>
          <a
            href="https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiIyOTUwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjUzODU2OTkwMTQ4ODI2MjQ5Nzk0OTczNjAyMzU1Mjc2ODQ2MjU5MTIwNjA4NTAwNTIxNDA0MDA5NzIxNjc5NjM3MDAzMTUzNDI2MTgxIiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHgxOTI3NUU5ZkQ3MjE5MDZGMjcxNUQ0Yjc4NjgxYjQ5ZGE1MDg4MTE3IiwicmVxdWVzdGVkQW1vdW50IjoiMjk1MDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweDQ0Q2ExNURiMTAxZkQxYzE5NDQ2N0RiNkFGMGM2N0M2QmJGNEFCNTEiLCJzaWduYXR1cmUiOiIweDg3NzQ2Mjk4Y2ZkMTRmMTFmOGY4NTNlNDk2ZTc1ZTQ2YmZhYzBmZmEwYjk0NmFjNjJmNDEwYTYyYjkyZDQ1NzAzZmEzMjQ4ZDJjZDhmNGNiOGI4ZTkyZTEwZTk3YTJhMzEyYTkwYTE5YmVhYjgwZThkMDE5YTkwNGUwNjFmYWRiMWIiLCJuZXR3b3JrSWQiOjEwMH1d"
          >
            [ 29.5 WXDAI ]</a
          >
        </h3>
        <h6>@molecula451</h6></b
      >
    </summary>
    <h6>Contributions Overview</h6>
<table><thead>
<tr><th>View</th><th>Contribution</th><th>Count</th><th>Reward</th>
</thead><tbody>
<tr><td>Issue</td><td>Comment</td><td>4</td><td>18.3</td></tr>
<tr><td>Review</td><td>Comment</td><td>3</td><td>11.2</td></tr>
</tbody></table>
    <h6>Conversation Incentives</h6><table><thead><tr><th>Comment</th><th>Formatting</th><th>Relevance</th><th>Reward</th></tr></thead><tbody><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/895#issuecomment-1939812859">i'm likely good with `require()` i would focus in gas optimizati...</a></h6></td><td><details><summary>8.8</summary>
<pre>li:
  count: 3
  score: "3"
  words: 3
code:
  count: 1
  score: "1"
  words: 1
</pre>
</details></td><td>0.7</td><td>8.8</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/895#issuecomment-1940425294">> custom errors are preferred over require/assert. This definate...</a></h6></td><td><details><summary>5.4</summary>
<pre>code:
  count: 1
  score: "1"
  words: 1
</pre>
</details></td><td>0.73</td><td>5.4</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/895#issuecomment-1940429868">> I believe the contracts is being deployed on Ethereum mainnet....</a></h6></td><td>1.4</td><td>0.45</td><td>1.4</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/895#issuecomment-1940464897">custom erros can also be inside `require()` that's why the chang...</a></h6></td><td><details><summary>2.7</summary>
<pre>code:
  count: 1
  score: "1"
  words: 1
</pre>
</details></td><td>0.51</td><td>2.7</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/pull/896#issuecomment-1941644623">Please fix the build actions as some are not passing...</a></h6></td><td>1</td><td>0.31</td><td>1</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/pull/896#issuecomment-1943256893">Yeah i think the PR won't make it either as the such refactors s...</a></h6></td><td>7.7</td><td>0.68</td><td>7.7</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/pull/896#issuecomment-1944485579">it looks like it took action on the PR closing but not on the is...</a></h6></td><td>2.5</td><td>0.59</td><td>2.5</td></tr></tbody></table>
  </details>
  

  <details>
    <summary>
      <b
        ><h3>
          <a
            href="https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiIyMTIwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjQ0NzAxNDUyNTAwMjk1OTU3ODc0NjUxOTU1Nzc2MjA0MjkxMzMwNTI1MDU5NjAwNjU1MzE1NTEzNTUzMzIyMDE4MTY2NzMwNDQ3MDgzIiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHg3ZTkyNDc2RDY5RmYxMzc3YThiNDUxNzZiMTgyOUM0QTU1NjY2NTNhIiwicmVxdWVzdGVkQW1vdW50IjoiMjEyMDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweDQ0Q2ExNURiMTAxZkQxYzE5NDQ2N0RiNkFGMGM2N0M2QmJGNEFCNTEiLCJzaWduYXR1cmUiOiIweGZkNWU2NDc2OTNlZGU3MzhhYzQ4MjU4MmVkY2JkNWU4MGY2MTA1NjY2MjZiNmMwM2ExNDg3YjFkNWY2NzJhMWYyNDkxMjA0YzMzNDI0NGNhMThkZTU5Nzc2NDViNTA3ZTc5NjExMTk0ODYzYWNkMzY4ZmQ3ZjdkZDM3OTJlYjZiMWMiLCJuZXR3b3JrSWQiOjEwMH1d"
          >
            [ 21.2 WXDAI ]</a
          >
        </h3>
        <h6>@gitcoindev</h6></b
      >
    </summary>
    <h6>Contributions Overview</h6>
<table><thead>
<tr><th>View</th><th>Contribution</th><th>Count</th><th>Reward</th>
</thead><tbody>
<tr><td>Review</td><td>Comment</td><td>1</td><td>21.2</td></tr>
</tbody></table>
    <h6>Conversation Incentives</h6><table><thead><tr><th>Comment</th><th>Formatting</th><th>Relevance</th><th>Reward</th></tr></thead><tbody><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/pull/896#issuecomment-1943685451">Hi everyone, I am back. I analysed the changes. Now I see where ...</a></h6></td><td><details><summary>21.2</summary>
<pre>li:
  count: 3
  score: "3"
  words: 43
</pre>
</details></td><td>0.61</td><td>21.2</td></tr></tbody></table>
  </details>
  

  <details>
    <summary>
      <b
        ><h3>
          <a
            href="https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiI4OTgwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjYxNDI4MjkwMzUyNDg5MDk2ODAzODA3NjI0NTA5MTYzOTIwMjExNjE2NTc4ODE5NjU3OTMzNDIwOTE2NDI0OTE5MTk0NDIyMTE4MjUyIiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHg5RWEzZWZhM0YxMTQ1QTQ2YzRlRWMzNEI1YTk5NURlNTcwYjgwNTBiIiwicmVxdWVzdGVkQW1vdW50IjoiODk4MDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweDQ0Q2ExNURiMTAxZkQxYzE5NDQ2N0RiNkFGMGM2N0M2QmJGNEFCNTEiLCJzaWduYXR1cmUiOiIweGU3ZGI1Mzc3MTNlMjlkYWQwY2U5Y2ZmMzhkYjcxYzkyYmE5MmY4MTNjNjU4OWQ5YWVjMTRhYTU1ZTFlNWY0OTMzYWY3NGU4N2I5ZWYyMDdlN2U1YzllYjc1ODBkMzIzNWU1OTQ1ZjQ4MTZjMzVmNTliMzBmZjQzODAwNzVkMjM1MWMiLCJuZXR3b3JrSWQiOjEwMH1d"
          >
            [ 89.8 WXDAI ]</a
          >
        </h3>
        <h6>@0xRizwan</h6></b
      >
    </summary>
    <h6>Contributions Overview</h6>
<table><thead>
<tr><th>View</th><th>Contribution</th><th>Count</th><th>Reward</th>
</thead><tbody>
<tr><td>Issue</td><td>Specification</td><td>1</td><td>7.2</td></tr>
<tr><td>Issue</td><td>Comment</td><td>3</td><td>44.6</td></tr>
<tr><td>Review</td><td>Comment</td><td>2</td><td>38</td></tr>
</tbody></table>
    <h6>Conversation Incentives</h6><table><thead><tr><th>Comment</th><th>Formatting</th><th>Rele

**Comment by 0x4007** [comment]
Looks like the qualitative analysis is no longer applying its multiplier. I see on gitcoindev's comment that it clearly is not doing anything: raw score of 21.2 with a relevance of 0.61 should yield 12.932 

Looks like I already filed the issue here

- https://github.com/ubiquibot/comment-incentives/issues/8

**Comment by 0xRizwan** [comment]
@pavlovcik @molecula451 and team, 

Thank you.
