### ISSUE TITLE
Fuzzing tests

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#925]
We should implement fuzzing tests for [LibUbiquityPool](https://github.com/ubiquity/ubiquity-dollar/blob/a1b11e1b944227144d7cc19ab320220d9fce8b69/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol). I think it would be enough to fuzz only "user scenarios":
- [Dollar token mint](https://github.com/ubiquity/ubiquity-dollar/blob/a1b11e1b944227144d7cc19ab320220d9fce8b69/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L486)
- [Dollar token redeem](https://github.com/ubiquity/ubiquity-dollar/blob/a1b11e1b944227144d7cc19ab320220d9fce8b69/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L594)
- [collecting redemption](https://github.com/ubiquity/ubiquity-dollar/blob/a1b11e1b944227144d7cc19ab320220d9fce8b69/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L710)

Possible solutions for fuzzing tests (I would simply start with foundry since we're using it as a development framework + it also contains invariant testing):
- https://book.getfoundry.sh/forge/fuzz-testing
- https://github.com/crytic/echidna
- https://github.com/crytic/medusa

What should be done:
1. Impelent fuzzing tests for the scenarios described above (you may create them in a separate test file like `UbiquityPoolFacet.fuzz.t.sol` so we could distinguish unit and fuzz tests)
2. Setup testing CI this way:
a) On PR fuzzing tests should run with a small number of runs (so that we could merge PRs fast)
b) On merge to the `development` branch fuzzing tests should run with a great number of runs to test many cases (keep in mind that github action runnners can run for 6 hours)

**Comment by 0x4007** [comment]
I thought there was a reason why we didn't implement echidna when I asked about it

**Comment by rndquu** [comment]
> I thought there was a reason why we didn't implement echidna when I asked about it

At that time we didn't have a clear scope of what to fuzz. Now we have the [LibUbiquityPool](https://github.com/ubiquity/ubiquity-dollar/blob/a1b11e1b944227144d7cc19ab320220d9fce8b69/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol) which is going to be deployed on mainnet, so the contract scope is clear.

**Comment by rndquu** [comment]
> I thought there was a reason why we didn't implement echidna when I asked about it

I think that auditors from our 1st Sherlock audit have already performed all of the fuzz, invariant and formal verification tests so it makes sense to set a normal priority for:
- https://github.com/ubiquity/ubiquity-dollar/issues/925
- https://github.com/ubiquity/ubiquity-dollar/issues/563
- https://github.com/ubiquity/ubiquity-dollar/issues/926

**Comment by gitcoindev** [comment]
> > I thought there was a reason why we didn't implement echidna when I asked about it
> 
> I think that auditors from our 1st Sherlock audit have already performed all of the fuzz, invariant and formal verification tests so it makes sense to set a normal priority for:
> 
> * [Fuzzing tests #925](https://github.com/ubiquity/ubiquity-dollar/issues/925)
> * [Invariant Testing #563](https://github.com/ubiquity/ubiquity-dollar/issues/563)
> * [Formal verification #926](https://github.com/ubiquity/ubiquity-dollar/issues/926)

Good point, I remember that quite a few issues were detected with different fuzzers on top of manual code reviews.

**Comment by gitcoindev** [comment]
> ```diff
> ! Too many assigned issues, you have reached your max limit
> ```

I will work on this behind the scenes and re-start the bot when the other issues are closed.

**Comment by 3scava1i3r** [comment]
@gitcoindev do you mind if i work on this one,if you have other tasks?

**Comment by gitcoindev** [comment]
> @gitcoindev do you mind if i work on this one,if you have other tasks?

Hi @3scava1i3r I have already started (the other tasks are finished, just waiting to be officially closed), but there is good news for you. We have a twin task for invariant tests here: https://github.com/ubiquity/ubiquity-dollar/issues/563 , would you mind picking that one instead?

**Comment by gitcoindev** [comment]
@3scava1i3r please confirm, whether you would be fine working on the twin task mentioned in the comment above - invariant test. If you are willing to work on this, please execute start command in https://github.com/ubiquity/ubiquity-dollar/issues/563 and the task will be automatically assigned to you.

**Comment by 0xJoichiro** [comment]
Hey there! @gitcoindev  👋 I've been working on the 'Better Security' tasks and wanted to ask for some assistance. I tried using the 'start' command to pick a task, but it doesn't seem to be working for me.

I've made some progress and don't want to interrupt the workflow or cause any issues. Could you please guide me on how 
to pick a task properly, so we can ensure a smooth collaboration?
Thank you so much for your time and help! 🙏 Really excited to contribute to this project!

**Comment by 3scava1i3r** [comment]
> @3scava1i3r please confirm, whether you would be fine working on the twin task mentioned in the comment above - invariant test. If you are willing to work on this, please execute start command in https://github.com/ubiquity/ubiquity-dollar/issues/563 and the task will be automatically assigned to you.

No sir,I will find something else to work on then

**Comment by gitcoindev** [comment]
Hi @0xJoichiro . Let's try to fix picking the task for you. There are a few commands available in the workflow. If you type `/help` command like I will do below, all the commands will be listed. In order to start a task, you just need to type `/start` in comment. Please let me know which tasks you have problem with and let's try to assign this to you. After you execute `/start` command you should open a draft pull request within a time frame mentioned in the issue label. The draft pull request does not need to have any major changes, can be just a comment. If you push code to the pull request branch and on a daily basis add comments to the issue you are working on, the bot will keep the task assigned to you until you solve it.

**Comment by 0xJoichiro** [comment]
> Hi @0xJoichiro . Let's try to fix picking the task for you. There are a few commands available in the workflow. If you type `/help` command like I will do below, all the commands will be listed. In order to start a task, you just need to type `/start` in comment. Please let me know which tasks you have problem with and let's try to assign this to you. After you execute `/start` command you should open a draft pull request within a time frame mentioned in the issue label. The draft pull request does not need to have any major changes, can be just a comment. If you push code to the pull request branch and on a daily basis add comments to the issue you are working on, the bot will keep the task assigned to you until you solve it.

understood currently working on https://github.com/ubiquity/ubiquity-dollar/issues/927 using openzeplin defender

**Comment by molecula451** [comment]
fuzzing testing upcoming? @gitcoindev

**Comment by gitcoindev** [comment]
> fuzzing testing upcoming? @gitcoindev

Yes, I will open a pull request until Friday EOD.

**Comment by gitcoindev** [comment]
I (no AI involved) identified the following properties of the system in case of mint, redeem and collection redemption :

Dollar token mint properties:

1. Given proper amount of governance tokens and collateral tokens for non 1-to-1 mint, when Dollar price is too low for the mint price threshold, no Dollar tokens can be minted. The same applies for 1-to-1 mint with governance tokens only.
2. If minimal amount of Dollars requested to be minted is higher than amount that can be minted, including the subtracted minting fee, no Dollar tokens can be minted with `Dollar slippage` returned.
3. If provided amount of collateral is not enough to cover the mint, no Dollar tokens can be minted with `Collateral slippage` returned.
4. If provided amount of governance tokens is not enough to cover the mint for 1-to-1 and fractional mint, no Dollar tokens can be minted with `Governance slippage` returned.
5. The Dollars can be minted for collateral ratio to governance tokens between 0 to 100. This means that it should be possible to mint Dollar tokens just providing collateral tokens, just providing governance tokens or the combination of both that will satisfy total collateral needed to mint given amount of tokens.

Dollar token redeem properties:

1. Dollar cannot be redeemed if the the dollar price is above the pool threshold, returning `Dollar price too high`.
2. There must be sufficient amount of collateral in the pool to redeem dollars.
3. If amount of collateral requested to redeem is higher then calculated based on current price, `Collateral slippage` is returned and Dollars cannot be redeemed.
4. If amount of governance tokens requested to redeem is higher then calculated based on current price, `Governance slippage` is returned and Dollars cannot be redeemed.
5. The Dollars can be redeemed for collateral ratio to governance tokens between 0 to 100. This means that it should be possible to redeem just collateral tokens, just governance tokens or the combination of both that will satisfy total collateral needed to redeem given amount of Dollar tokens.

Collecting redemption properties:

1. Given any amount of governance tokens and collateral token balances that are available to be collected after the redemption, they can be collected after certain number of blockchain blocks pass since the last redemption happened for the same account.

Those properties will be a base for the fuzz tests. Multiple inputs shall be provided by the test harness to test each of the properties.

**Comment by rndquu** [comment]
> I (no AI involved) identified the following properties of the system in case of mint, redeem and collection redemption :
> 
> Dollar token mint properties:
> 
> 1. Given proper amount of governance tokens and collateral tokens for non 1-to-1 mint, when Dollar price is too low for the mint price threshold, no Dollar tokens can be minted. The same applies for 1-to-1 mint with governance tokens only.
> 2. If minimal amount of Dollars requested to be minted is higher than amount that can be minted, including the subtracted minting fee, no Dollar tokens can be minted with `Dollar slippage` returned.
> 3. If provided amount of collateral is not enough to cover the mint, no Dollar tokens can be minted with `Collateral slippage` returned.
> 4. If provided amount of governance tokens is not enough to cover the mint for 1-to-1 and fractional mint, no Dollar tokens can be minted with `Governance slippage` returned.
> 5. The Dollars can be minted for collateral ratio to governance tokens between 0 to 100. This means that it should be possible to mint Dollar tokens just providing collateral tokens, just providing governance tokens or the combination of both that will satisfy total collateral needed to mint given amount of tokens.
> 
> Dollar token redeem properties:
> 
> 1. Dollar cannot be redeemed if the the dollar price is above the pool threshold, returning `Dollar price too high`.
> 2. There must be sufficient amount of collateral in the pool to redeem dollars.
> 3. If amount of collateral requested to redeem is higher then calculated based on current price, `Collateral slippage` is returned and Dollars cannot be redeemed.
> 4. If amount of governance tokens requested to redeem is higher then calculated based on current price, `Governance slippage` is returned and Dollars cannot be redeemed.
> 5. The Dollars can be redeemed for collateral ratio to governance tokens between 0 to 100. This means that it should be possible to redeem just collateral tokens, just governance tokens or the combination of both that will satisfy total collateral needed to redeem given amount of Dollar tokens.
> 
> Collecting redemption properties:
> 
> 1. Given any amount of governance tokens and collateral token balances that are available to be collected after the redemption, they can be collected after certain number of blockchain blocks pass since the last redemption happened for the same account.
> 
> Those properties will be a base for the fuzz tests. Multiple inputs shall be provided by the test harness to test each of the properties.

Sounds good. The same "properties" could be later converted to [invariants](https://book.getfoundry.sh/forge/invariant-testing).

**Comment by gitcoindev** [comment]
Draft pull request with a skeleton for tests opened. I will mark it as ready for review when all the fuzz tests based on properties above will be implemented.

**Comment by gitcoindev** [comment]
Pull request ready for the review.

**Comment by gitcoindev** [comment]
> ```diff
> ! Too many assigned issues, you have reached your max limit
> ```

Interesting, I received a notification in the pull request that bot unassigned me, so I tried to re-assign myself.
